# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-762dc7c0-6c01-49a0-a194-589d9c07dda9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-762dc7c0-6c01-49a0-a194-589d9c07dda9".device = "/dev/disk/by-uuid/762dc7c0-6c01-49a0-a194-589d9c07dda9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF11-558E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-e08190a4-c01b-48ff-b20e-87f82a33ecbf"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
